-- ════════════════════════════════════════════════════════════════════════
--  BBDD comercial iMercados · Fase 3 — Tabla de STAGING (carga en crudo)
--  Idempotente: se puede volver a correr sin romper nada.
--  No toca ninguna tabla existente.
-- ════════════════════════════════════════════════════════════════════════

create table if not exists public.staging_contactos_imercados (
  id                     bigint generated by default as identity primary key,
  fila_origen            int,          -- nº de fila en el Excel (trazabilidad)
  lote                   int,          -- nº de lote (carga reanudable)
  columna1               text,
  razon_social           text,
  nombre_fantasia        text,
  persona                text,
  trabajador_en_empresa  text,
  cargo                  text,
  correo_corporativo     text,
  correo_persona         text,
  telefono_1             text,
  telefono_2             text,
  rubro                  text,
  industria1             text,
  industrias2            text,
  industrias4            text,
  cargado_en             timestamptz not null default now()
);

comment on table public.staging_contactos_imercados is
  'Copia CRUDA del Excel BBDD iMercados (14 columnas como texto). Origen para transformar a las tablas definitivas. No usar directo en la app.';
