-- ════════════════════════════════════════════════════════════════════════
--  BBDD comercial iMercados · Fase 4 — Tablas DEFINITIVAS
--  Idempotente (create table if not exists). No toca tablas existentes.
--  Se APLICA en la Fase 4 (carga definitiva), tras revisar los CSV de control.
-- ════════════════════════════════════════════════════════════════════════

-- ── Empresas ──
create table if not exists public.companies (
  id                bigint generated by default as identity primary key,
  razon_social      text not null,          -- original
  razon_social_norm text not null,          -- normalizado (clave de dedup)
  nombre_fantasia   text,
  rubro             text,                    -- Proveedor / Productor / Instituciones y Organismos / Universidades / Exploración
  rut               text,                    -- NULL por ahora (enriquecer después)
  region            text,                    -- NULL por ahora
  comuna            text,                    -- NULL por ahora
  direccion         text,                    -- NULL por ahora
  sitio_web         text,                    -- NULL por ahora
  tamano            text,                    -- NULL por ahora
  telefono_central  text,                    -- NULL por ahora
  fuente            text not null default 'iMercados',
  fecha_carga       timestamptz not null default now(),
  created_at        timestamptz not null default now(),
  constraint companies_razon_social_norm_key unique (razon_social_norm)
);

-- ── Industrias por empresa (reemplaza Industria1/2/4; el origen no trae "Industrias3") ──
create table if not exists public.company_industries (
  id         bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  industria  text not null,
  orden      int not null,   -- 1=Industria1, 2=Industrias2, 4=Industrias4
  fuente     text not null default 'iMercados',
  created_at timestamptz not null default now(),
  constraint company_industries_uq unique (company_id, industria)
);

-- ── Personas (una fila por persona real, tras deduplicar) ──
create table if not exists public.contacts (
  id                          bigint generated by default as identity primary key,
  nombre_completo             text not null,   -- ORIGINAL intacto ("Persona")
  nombre_tentativo            text,
  apellido_tentativo          text,
  nombre_separacion_confiable boolean not null default false,
  nombre_alternativo          text,            -- "Trabajador en empresa" solo si difiere
  nota_original               text,            -- rescatado de "Columna1"
  dedup_key                   text not null,   -- clave determinista de deduplicación
  revision_manual             boolean not null default false,  -- true en conflictos (mismo correo, nombres distintos)
  fuente                      text not null default 'iMercados',
  fecha_carga                 timestamptz not null default now(),
  created_at                  timestamptz not null default now(),
  constraint contacts_dedup_key_key unique (dedup_key)
);

-- ── Puente persona ↔ empresa (una persona puede estar en varias empresas) ──
create table if not exists public.contact_company (
  id           bigint generated by default as identity primary key,
  contact_id   bigint not null references public.contacts(id) on delete cascade,
  company_id   bigint not null references public.companies(id) on delete cascade,
  cargo        text,
  es_principal boolean not null default false,
  fuente       text not null default 'iMercados',
  created_at   timestamptz not null default now(),
  constraint contact_company_uq unique (contact_id, company_id)
);

-- ── Correos (varios por persona; el corporativo es principal si existe) ──
create table if not exists public.contact_emails (
  id           bigint generated by default as identity primary key,
  contact_id   bigint not null references public.contacts(id) on delete cascade,
  email        text not null,                 -- minúscula, sin espacios
  tipo         text not null,                 -- 'corporativo' | 'personal'
  valido       boolean not null default false,
  es_principal boolean not null default false,
  fuente       text not null default 'iMercados',
  created_at   timestamptz not null default now(),
  constraint contact_emails_uq  unique (contact_id, email),
  constraint contact_emails_tipo_chk check (tipo in ('corporativo','personal'))
);

-- ── Teléfonos (resuelve celdas con varios números, extranjeros y "a revisar") ──
create table if not exists public.contact_phones (
  id          bigint generated by default as identity primary key,
  contact_id  bigint not null references public.contacts(id) on delete cascade,
  numero_raw  text not null,                 -- ORIGINAL preservado
  numero_e164 text,                          -- +569.../+562.../+34... cuando se puede
  tipo        text,                          -- 'movil' | 'fijo' | 'desconocido'
  pais        text,                          -- ISO-2: 'CL', 'ES', ...
  valido      boolean not null default false,
  orden       int not null default 1,
  fuente      text not null default 'iMercados',
  created_at  timestamptz not null default now(),
  constraint contact_phones_uq unique (contact_id, numero_raw)
);

comment on table public.companies        is 'Empresas únicas (dedup por razon_social_norm).';
comment on table public.contacts         is 'Personas reales (dedup por dedup_key: correo+nombre, o nombre+empresa si no hay correo).';
comment on table public.contact_company  is 'Puente N:N persona-empresa con cargo.';
